name: dart_vlc
description: Flutter media playback, broadcast, recording & chromecast library. Based on libVLC & libVLC++.
version: 0.1.5
homepage: https://github.com/alexmercerind/dart_vlc
repository: https://github.com/alexmercerind/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dart_vlc_ffi: ^0.1.3
  path: ^1.8.0
  path_provider: ^2.0.1
  audio_video_progress_bar: ^0.4.0
  window_size:
    git:
      url: git://github.com/alexmercerind/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: da98a3b5a0e2b9425fbcb2a3e4b4ba50754abf93

flutter:
  # No platform channel implementation after migration to FFI.
  plugin:
    platforms:
      windows:
        pluginClass: DartVlcPlugin
      linux:
        pluginClass: DartVlcPlugin
      macos:
        pluginClass: DartVlcPlugin

